### ISSUE TITLE
Checkbox for Multiselect not working properly!

### ISSUE THREAD

**Issue by HariharanEswaran** [crux-lab/sectioned-recycler-view#1]
Firast of all,your library was good.But i have to faced one issue.i.e. ' If i  used checkbox in childitems,when i was select some items then automatically some items are checked(selected) ' ..please find the issue,plese help me,Thanks in Advance

**Comment by lizapopova** [comment]
Hi @HariharanEswaran,
Unfortunately, I can't detect the problem based on your message. Please give me more details on it (share code etc.).
Seems like when the items are reused the checked state is not updated. Are you sure you apply the selected state to each item in onBind?
Can you also check if this problem reproduces without using SectionedRecyclerView library?

**Comment by lizapopova** [comment]
Closing as obsolete.
