### ISSUE TITLE
Add library to Maven Central now that JCenter will be sunset

### ISSUE THREAD

**Issue by VincentJoshuaET** [crux-lab/sectioned-recycler-view#13]

**Comment by lizapopova** [comment]
Hi @VincentJoshuaET,
Given that JCenter will be sunsetted, I've already moved the library to **JitPack repository**. Now you can use it as follows:
1. Add the JitPack repository to your project's build.gradle file:

```
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
```

2. Add the dependency to your module's build.gradle file:
```
implementation 'com.github.crux-lab:sectioned-recycler-view:1.1.1'
```

**Note**: *before* it was `implementation 'com.cruxlab:sectionedrecyclerview:1.1.0'`

I hope this will work for you.
