### ISSUE TITLE
Scroll to Section

### ISSUE THREAD

**Issue by jazeelmohd** [crux-lab/sectioned-recycler-view#2]
Hi, thanks for the great library.

I would like to know how can I scroll to a section on a click event, say a button click. It would be really helpful if you could provide me some insight into implementing this.

**Comment by lizapopova** [comment]
Hi @jazeelmohd, thank you for using the library!

To scroll within the RecyclerView you can use one of [RecyclerView#scrollToPosition](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView#scrollToPosition(int)) or [RecyclerView#smoothScrollToPosition](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView#smoothScrollToPosition(int)). These methods take as a parameter the global RecyclerView position. To determine it for a specific section, you can use [SectionDataManager](https://github.com/crux-lab/sectioned-recycler-view/blob/master/sectionedrecyclerview/src/main/java/com/cruxlab/sectionedrecyclerview/lib/SectionDataManager.java) which implements [PositionManager](https://github.com/crux-lab/sectioned-recycler-view/blob/master/sectionedrecyclerview/src/main/java/com/cruxlab/sectionedrecyclerview/lib/PositionManager.java) interface.

For example, to scroll to the header of the section #3, you can write the following code:
```
int sectionIndex = 2;
int firstItemPos = sectionDataManager.calcAdapterPos(sectionIndex, 0);
int headerPos = firstItemPos - 1;
recyclewView.smoothScrollToPosition(headerPos);
```
If your section is headerless, you can simply use `firstItemPos`.

If you need to scroll to the state in which selected section is at the very top and you are using `LinearLayoutManager`, you can use [`scrollToPositionWithOffset`](https://developer.android.com/reference/androidx/recyclerview/widget/LinearLayoutManager#scrollToPositionWithOffset(int,%20int)):
```
linearLayoutManager.scrollToPositionWithOffset(determinedPos, 0);
```
The general idea is that you can calculate the global RecyclerView position and then write the same logic as if you were using default RecyclerView adapter.

Let me know if my answer was helpful.

**Comment by jazeelmohd** [comment]
> Hi @jazeelmohd, thank you for using the library!
> 
> To scroll within the RecyclerView you can use one of [RecyclerView#scrollToPosition](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView#scrollToPosition(int)) or [RecyclerView#smoothScrollToPosition](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView#smoothScrollToPosition(int)). These methods take as a parameter the global RecyclerView position. To determine it for a specific section, you can use [SectionDataManager](https://github.com/crux-lab/sectioned-recycler-view/blob/master/sectionedrecyclerview/src/main/java/com/cruxlab/sectionedrecyclerview/lib/SectionDataManager.java) which implements [PositionManager](https://github.com/crux-lab/sectioned-recycler-view/blob/master/sectionedrecyclerview/src/main/java/com/cruxlab/sectionedrecyclerview/lib/PositionManager.java) interface.
> 
> For example, to scroll to the header of the section #3, you can write the following code:
> 
> ```
> int sectionIndex = 2;
> int firstItemPos = sectionDataManager.calcAdapterPos(sectionIndex, 0);
> int headerPos = firstItemPos - 1;
> recyclewView.smoothScrollToPosition(headerPos);
> ```
> 
> If your section is headerless, you can simply use `firstItemPos`.
> 
> If you need to scroll to the state in which selected section is at the very top and you are using `LinearLayoutManager`, you can use [scrollToPositionWithOffset](https://developer.android.com/reference/androidx/recyclerview/widget/LinearLayoutManager#scrollToPositionWithOffset(int,%20int)):
> 
> ```
> linearLayoutManager.scrollToPositionWithOffset(determinedPos, 0);
> ```
> 
> The general idea is that you can calculate the global RecyclerView position and then write the same logic as if you were using default RecyclerView adapter.
> 
> Let me know if my answer was helpful.

Thanks for the quick reply. It worked
