### ISSUE TITLE
Item Decoration

### ISSUE THREAD

**Issue by BossJC69** [crux-lab/sectioned-recycler-view#4]
How can I use an item decoration only if the item is not header?

**Comment by lizapopova** [comment]
Hi @BossJC69,
You can check if an item is a header using [SectionDataManager](https://github.com/crux-lab/sectioned-recycler-view/blob/master/sectionedrecyclerview/src/main/java/com/cruxlab/sectionedrecyclerview/lib/SectionDataManager.java) which implements [PositionManager](https://github.com/crux-lab/sectioned-recycler-view/blob/master/sectionedrecyclerview/src/main/java/com/cruxlab/sectionedrecyclerview/lib/PositionManager.java) interface. It contains `boolean isHeader(int adapterPos)` method, which returns true if the given global adapter position corresponds to a header.

So, for example, if you want to override `getItemOffsets` method only for non header items, you can write the following code (in Kotlin):
```
val adapterPos = parent.getChildAdapterPosition(view)
if (!posManager.isHeader(adapterPos)) {
    // Do what you want
}
```
Let me know if my answer was helpful.

**Comment by BossJC69** [comment]
It worked. Thank you.
