### ISSUE TITLE
How can I scroll particular header with your library

### ISSUE THREAD

**Issue by ddpatel2606** [crux-lab/sectioned-recycler-view#5]
Hello I want to develop this kind of functionality.

when I click on tab layout Item sectioned recycler-view auto scroll to particular header position.

![device-2020-07-25-171811](https://user-images.githubusercontent.com/4408862/88458848-7e7d6580-ceae-11ea-93ab-a93bba92fdc0.png)

Kindly advise me please, How can I achieved It.

Thanks

**Comment by lizapopova** [comment]
Hi @ddpatel2606, thank you for using the library!

To scroll within the RecyclerView you can use one of [RecyclerView#scrollToPosition](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView#scrollToPosition(int)) or [RecyclerView#smoothScrollToPosition](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView#smoothScrollToPosition(int)). These methods take as a parameter the global RecyclerView position. To determine it for a specific section, you can use [SectionDataManager](https://github.com/crux-lab/sectioned-recycler-view/blob/master/sectionedrecyclerview/src/main/java/com/cruxlab/sectionedrecyclerview/lib/SectionDataManager.java) which implements [PositionManager](https://github.com/crux-lab/sectioned-recycler-view/blob/master/sectionedrecyclerview/src/main/java/com/cruxlab/sectionedrecyclerview/lib/PositionManager.java) interface.

So, in your case, you have to write something like this:
```
tabLayout.addOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {
        @Override
        public void onTabSelected(TabLayout.Tab tab) {
             int sectionIndex = tab.getPosition();
             int firstItemPos = sectionDataManager.calcAdapterPos(sectionIndex, 0);
             int headerPos = firstItemPos - 1;
             recyclewView.smoothScrollToPosition(headerPos);
        }
        ...
});
```
If you need to scroll to the state in which selected section is at the very top and you are using `LinearLayoutManager`, you can use [scrollToPositionWithOffset](https://developer.android.com/reference/androidx/recyclerview/widget/LinearLayoutManager#scrollToPositionWithOffset(int,%20int)):
```
linearLayoutManager.scrollToPositionWithOffset(determinedPos, 0);
```
The general idea is that you can calculate the global RecyclerView position and then write the same logic as if you were using default RecyclerView adapter.

Let me know if my answer was helpful.

**Comment by ddpatel2606** [comment]
Yes, Its works perfect, You saved my so much time, thank you so much.
