### ISSUE TITLE
Hide section headers

### ISSUE THREAD

**Issue by PawelDecowski** [crux-lab/sectioned-recycler-view#8]
Is there a way to hide section headers after initialising?

```kt
val adapter = MyAdapter(true, true)
sectionDataManager.addSection(adapter, HEADER_TYPE)
```

Elsewhere:

```kt
adapter.isHeaderVisible = false
```

But the adapter doesn’t have `isHeaderVisible` property; it’s only a constructor argument.

**Comment by lizapopova** [comment]
Hi @PawelDecowski,
Yes, this can be achieved using `SectionAdapter#updateHeaderVisibility` method:
```
adapter.updateHeaderVisibility(false)
```

**Comment by PawelDecowski** [comment]
Awesome. Thank you @lizapopova!
